tracker/tracker/about/urls.py
from django.urls import path


app_name = 'about'

urlpatterns = [

]

tracker/tracker/tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/tracker/users/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change'),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset_form'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
]

tracker/tracker/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

tracker/tracker/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

tracker/tracker/templates/users/login.html
{% extends 'base.html' %}
{% block title %}Войти{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Войти на сайт
            </div>
            <div class="card-body">
                {% include 'includes/form_errors.html' %}
                <form method="post"
                {% if action_url %}
                action="{% url action_url %}"
                {% endif %}
                >
                {% csrf_token %}
                {% include 'includes/required_pattern_form.html' %}
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        Войти
                    </button>
                    <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                        Забыли пароль?
                    </a>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tracker/tracker/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Ваш пароль изменен
            </div>
            <div class="card-body">
                <p>Пароль успешно изменен</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tracker/tracker/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Изменения пароля{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 py-5">
        <div class="card">
            <div class="card-header">
                Изменить пароль
            </div>
            <div class="card-body">
                {% include 'includes/form_errors.html' %}

                <form method="post">
                    {% csrf_token %}
                    {% include 'includes/required_pattern_form.html' %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Изменить пароль
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

tracker/tracker/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Пароль изменен
            </div>
            <div class="card-body">
                <p>Пароль изменен</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tracker/tracker/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% if validlink %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Введите новый пароль
            </div>
            <div class="card-body">
                {% include 'includes/form_errors.html' %}
                <form method="post">
                    {% csrf_token %}
                    {% include 'includes/required_pattern_form.html' %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Новый пароль
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tracker/tracker/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Ссылка для восстановления пароля отправлена вам на почту{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Ссылка для восстановления пароля отправлена вам на почту</div>
            <div class="card-body">
                <p>роверьте почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tracker/tracker/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Чтобы сбросить старый пароль — введите
                адрес электронной почты, под которым вы регистрировались
            </div>
            {% include 'includes/required_pattern_form.html' %}

            <form method="post">
                {% csrf_token %}
                {% include 'includes/required_pattern_form.html' %}
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        Сбросить пароль
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

tracker/tracker/templates/users/signup.html
{% extends 'base.html' %}
{% block title %}Зарегистрироваться{% endblock %}
{% block header %}Регистрация{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-body">
                {% include 'includes/form_errors.html' %}
                <form method="post"
                {% if action_url %}
                action="{% url action_url %}"
                {% endif %}
                >
                {% csrf_token %}
                {% include 'includes/required_pattern_form.html' %}
                <div class="col-md-8 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        Зарегистрироваться
                    </button>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}