tracker/tracker/about/urls.py
from django.urls import path


app_name = 'about'

urlpatterns = [

]

tracker/tracker/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow, name='profile_unfollow'),
    path('search/', views.search_post, name='search_post'),

]

tracker/tracker/tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/tracker/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import constraints

User = get_user_model()


class Place(models.Model):
    name = models.CharField(max_length=154)
    keywords = models.CharField(max_length=154)

    def __str__(self):
        return self.name[:15]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Группы задач',
        help_text=''
    )
    description = models.TextField(
        max_length=255,
        verbose_name='Описание'
    )
    slug = models.SlugField(
        max_length=50,
        db_index=True,
        unique=True,
        verbose_name='URL'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField(
        max_length=200,
        verbose_name='Текст задачи',
        help_text='Введите текст задачи',
    )
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относится задача'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        related_name='comments',
        null=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        max_length=254,
        verbose_name='Комментарии'
    )
    created = models.DateTimeField('Дата публикации', auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = (
            constraints.UniqueConstraint(
                fields=('user', 'author'), name='follow_unique'),
        )
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

    def __str__(self):
        return self.user.username, self.author.username

tracker/tracker/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст задачи',
            'group': 'Группа'
        }
        help_text = {
            'text': 'Текст вашей записи',
            'group': 'Группа, к которой будет относится задача'
        }


class SearchPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text',)


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

tracker/tracker/posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from posts.forms import CommentForm, PostForm
from posts.models import Post, Group, User, Follow
from posts.utils import pagination


def index(request):
    posts = Post.objects.select_related('group', 'author').all()
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_post(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.select_related('group', 'author').all()
    page_obj = pagination(request, post_list)
    context = {
        "page_obj": page_obj,
        "group": group
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    profile_user = get_object_or_404(User, username=username)
    post_list = profile_user.posts.select_related('group', 'author').all()
    page_obj = pagination(request, post_list)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=profile_user
        ).exists()
    else:
        following = False
    context = {
        'page_obj': page_obj,
        'profile_user': profile_user,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related('group', 'author'),
                             pk=post_id)
    user = get_object_or_404(User,
                             username=post.author)
    post_number = user.posts.filter(author=user).count()
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'post_number': post_number,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    user_obj = request.user
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    context = {
        'form': form,
        'user_obj': user_obj,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post.objects.select_related().all(), pk=post_id)
    if post.author != request.user:
        return redirect('posts:index')
    form = PostForm(request.POST or None,
                    instance=post,
                    files=request.FILES or None)
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': True
        }
        return render(request, 'posts/create_post.html', context)
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post.objects.select_related('author', 'group'), id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post = Post.objects.filter(author__following__user=request.user)
    page_obj = pagination(request, post)
    follow = True
    context = {
        'page_obj': page_obj,
        'follow': follow,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author and Follow.objects.filter(
            user=request.user, author=author
    ).exists():
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', author)


def search_post(request):
    query = request.GET.get('q')
    post = Post.objects.filter(Q(text__icontains=query))
    page_obj = pagination(request, post)
    context = {
        "page_obj": page_obj
    }
    return render(request, 'posts/search_match_post.html', context)

tracker/tracker/templates/posts/includes/comment.html
{% for comment in comments %}
    <div class="media mb-4">
        <div class="media-body">
            <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                </a>
            </h5>
            <p>
                {{ comment.text|linebreaksbr }}
            </p>
        </div>
    </div>
{% endfor %}

tracker/tracker/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Предыдущая
            </a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <span class="page-link">{{ i }}</span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    Следующая
                </a>
            </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                Последняя
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

tracker/tracker/templates/posts/includes/site_card.html
{% load thumbnail %}
    {% for post in page_obj %}
        <div class="container py-5">
            <article>
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                        <a href="{% url 'posts:profile' post.author.username %}">Все задачи пользователя</a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>{{ post.text|linebreaksbr }}</p>
                {% thumbnail post.image '960x369' crop='center' upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
            </article>
            {% if post.group and show_group_link %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
        </div>
    {% endfor %}

tracker/tracker/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
    <div class="row my-3">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav -link {% if index%} active{% endif %}"
                   href="{% url 'posts:index' %}"
                   >
                   Все авторы
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if follow %}active{% endif %}"
                   href="{% url 'posts:follow_index' %}"
                   >
                Избранные авторы
                </a>
            </li>
        </ul>
    </div>
{% endif %}