tracker/tracker/about/urls.py
from django.urls import path


app_name = 'about'

urlpatterns = [

]

tracker/tracker/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow, name='profile_unfollow'),
    path('search/', views.search_post, name='search_post'),

]

tracker/tracker/tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/tracker/users/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change'),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset_form'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
]

tracker/tracker/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">F</span>astracker by AlieD3d</p>

tracker/tracker/templates/includes/form_errors.html
{% if form.errors %}
    {% for error in field.errors %}
        <div class="alert alert-danger">
            {{ error|escape }}
        </div>
    {% endfor %}
    {% for error in form.non_field_erorrs %}
        <div class="alert alert-danger">
            {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}

tracker/tracker/templates/includes/header.html
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'posts:index' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <span style="color:red; font-size: 25px;">F</span>
            <span style="font-size: 20px">astTracker</span>
        </a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            {% with request.resolver_match.view_name as view_name %}
              <li class="nav-item mx-2">
                  <a href="#" class="nav-link px-2 text-white" style="font-size: 18px;">
                      О нас
                  </a>
              </li>
            {% endwith %}
            {% if user.is_authenticated %}
                {% with request.resolver_match.view_name as view_name %}
                    <li class="nav-item mx-2">
                        <a href="{% url 'posts:post_create' %}" class="nav-link px-2 text-white" style="font-size: 18px;">
                            Новая задача
                        </a>
                    </li>
                {% endwith %}
                {% with request.resolver_match.view_name as view_name %}
                    <li class="nav-item mx-2">
                        <a href="{% url 'logout' %}" class="nav-link px-2 text-white" style="font-size: 19px;"">
                            Выйти
                        </a>
                    </li>
                {% endwith %}
                <li>
                    Пользователь: {{ user.username }}
                </li>
                {% else %}
                    {% with request.resolver_match.view_name as view_name %}
                    <li class="nav-item mx-2">
                        <a href="{% url 'users:login' %}" class="nav-link px-2 text-white" style="font-size: 19px;">
                            Войти
                        </a>
                    </li>
                {% endwith %}
                {% with request.resolver_match.view_name as view_name %}
                    <li class="nav-item mx-2">
                        <a href="{% url 'users:signup' %}" class="nav-link px-2 text-white" style="font-size: 18px;">
                            Регистрация
                        </a>
                    </li>
                {% endwith %}
            {% endif %}
        </ul>
        <form class="d-flex" method="get" action="{% url 'posts:search_post' %}">
        
          <input type="search" class="form-control form-control-dark me-2" placeholder="Поиск по задачам..." aria-label="Поиск" name="q">
          <button type="submit" class="btn btn-outline-success">Поиск</button>
        </form>
      </div>
    </div>
  </header>

tracker/tracker/templates/includes/required_pattern_form.html
{% load user_filters %}
{% for field in form %}
    <div class="form-group row my-3">
        <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
            {{ field.label }}
            {% if field.field.required %}
                <span class="required text-danger">*</span>
            {% endif %}
        </label>
    </div>
    <div class="col-md-12">
        {{ field|addclass:"form-control" }}
        {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-mutted">
                {{ field.help_text|safe }}
            </small>
        {% endif %}
{% endfor %}
    </div>